# Generated by Django 4.1.7 on 2023-05-07 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitados', '0002_alter_invitado_respuesta'),
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.evento')),
                ('invitado', models.ManyToManyField(to='invitados.invitado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
