# Generated by Django 4.1.7 on 2023-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='descripcion',
            field=models.CharField(max_length=280),
        ),
    ]
