# Generated by Django 4.1.7 on 2023-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_remove_reminder_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
