# Generated by Django 4.1.7 on 2023-04-09 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('tasks', '0003_task_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='evento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.evento'),
        ),
    ]
