# Generated by Django 4.1.7 on 2023-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fechaTer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
