# Generated by Django 4.1.7 on 2023-04-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
                ('respuesta', models.CharField(max_length=2)),
                ('evento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.evento')),
            ],
        ),
    ]
