# Generated by Django 4.1.7 on 2023-04-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='respuesta',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
